name: Update Credly Badges

on:
  schedule:
    # Daily at 02:30 UTC
    - cron: "30 2 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-badges:
    name: Update README with Credly Badges

    runs-on: ubuntu-latest

    steps:
      - name: Update Credly badges
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: vuongdam2k01
          NUMBER_LAST_BADGES: 6
          COMMIT_MESSAGE: "chore: update Credly badges"